services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app/astro_project
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
     - PYTHONUNBUFFERED=1
  redis:
    image: redis:7
    ports:
      - "6379:6379"