# Generated by Django 4.2.21 on 2025-05-20 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('matched_aspects', models.JSONField(blank=True, null=True)),
                ('ai_interpretation', models.TextField(blank=True, null=True)),
                ('is_ai_unlocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_initiator', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_a', 'user_b')},
            },
        ),
    ]
