# Generated by Django 4.2.30 on 2026-07-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscore',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='ai_model_used',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='ai_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
