# Generated by Django 4.2.21 on 2025-05-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_match_gender'),
        ('matching', '0002_matchrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', '喜歡'), ('dislike', '不喜歡')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_actions', to='accounts.userprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_actions', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.DeleteModel(
            name='MatchRequest',
        ),
    ]
