# Generated by Django 4.2.21 on 2025-05-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_match_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_age_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_age_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
