# Generated by Django 5.2 on 2025-04-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBirthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_day', models.IntegerField()),
                ('birth_hour', models.IntegerField()),
                ('birth_minute', models.IntegerField()),
                ('birth_second', models.IntegerField(blank=True, null=True)),
                ('birth_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('birth_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('birth_location', models.CharField(blank=True, max_length=100, null=True)),
                ('zodiac_sign', models.CharField(blank=True, max_length=20, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_info', to='accounts.userprofile')),
            ],
        ),
    ]
