# Generated by Django 4.2.30 on 2026-07-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbirthinfo',
            name='chart_edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='last_chart_edit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
