# Generated by Django 4.2.20 on 2025-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbirthinfo',
            name='moon_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
