# Generated by Django 4.2.20 on 2025-05-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userbirthinfo_moon_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbirthinfo',
            old_name='zodiac_sign',
            new_name='sun_sign',
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='jupiter_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='mars_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='mercury_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='neptune_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='pluto_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='saturn_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='uranus_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='venus_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
