# Generated by Django 4.2.20 on 2025-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_zodiac_sign_userbirthinfo_sun_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbirthinfo',
            name='ascendant_sign',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='descendant_sign',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='ic_sign',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userbirthinfo',
            name='mc_sign',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
