# Generated by Django 4.2.20 on 2025-05-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userbirthinfo_birth_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='ascendant_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='descendant_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='ic_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='jupiter_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='mars_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='mc_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='mercury_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='moon_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='neptune_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='pluto_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='saturn_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='sun_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='uranus_sign',
        ),
        migrations.RemoveField(
            model_name='userbirthinfo',
            name='venus_sign',
        ),
    ]
