# Generated by Django 4.2.21 on 2025-05-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userbirthinfo_ascendant_sign_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
