# Generated by Django 4.2.30 on 2026-07-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetposition',
            name='is_retrograde',
            field=models.BooleanField(default=False),
        ),
    ]
