# Generated by Django 4.2.21 on 2025-05-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetposition',
            name='degree_in_sign',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
