# Generated by Django 4.2.21 on 2025-05-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_planetposition_degree_in_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planetposition',
            old_name='degree_in_sign',
            new_name='correct_degree',
        ),
    ]
